export interface DefaultItem {
  name: string;
  value: number;
  category: string;
  emoji: string;
}

export const DEFAULT_ITEMS: DefaultItem[] = [
  { name: 'Maize flour 2kg', value: 250, category: 'Food Staples', emoji: '🌽' },
  { name: 'Maize flour 1kg', value: 130, category: 'Food Staples', emoji: '🌽' },
  { name: 'Wheat flour 2kg', value: 280, category: 'Food Staples', emoji: '🌾' },
  { name: 'Wheat flour 1kg', value: 150, category: 'Food Staples', emoji: '🌾' },
  { name: 'Rice 1kg', value: 180, category: 'Food Staples', emoji: '🍚' },
  { name: 'Rice 2kg', value: 350, category: 'Food Staples', emoji: '🍚' },
  { name: 'Sugar 1kg', value: 150, category: 'Food Staples', emoji: '🧂' },
  { name: 'Sugar 2kg', value: 280, category: 'Food Staples', emoji: '🧂' },
  { name: 'Salt 1kg', value: 60, category: 'Food Staples', emoji: '🧂' },
  { name: 'Cooking oil 500ml', value: 180, category: 'Food Staples', emoji: '🫒' },
  { name: 'Cooking oil 1L', value: 300, category: 'Food Staples', emoji: '🫒' },
  { name: 'Cooking oil 2L', value: 550, category: 'Food Staples', emoji: '🫒' },
  { name: 'Margarine 250g', value: 120, category: 'Food Staples', emoji: '🧈' },
  { name: 'Butter 250g', value: 180, category: 'Food Staples', emoji: '🧈' },
  { name: 'Baking flour', value: 200, category: 'Food Staples', emoji: '🥡' },
  { name: 'Baking powder', value: 80, category: 'Food Staples', emoji: '🥡' },
  { name: 'Yeast', value: 60, category: 'Food Staples', emoji: '🥡' },
  { name: 'Cornstarch', value: 90, category: 'Food Staples', emoji: '🥡' },
  { name: 'Oats', value: 220, category: 'Food Staples', emoji: '🥣' },
  { name: 'Semolina', value: 160, category: 'Food Staples', emoji: '🥣' },
  { name: 'White bread', value: 60, category: 'Bread & Bakery', emoji: '🍞' },
  { name: 'Brown bread', value: 70, category: 'Bread & Bakery', emoji: '🍞' },
  { name: 'Sweet buns', value: 40, category: 'Bread & Bakery', emoji: '🥐' },
  { name: 'Mandazi', value: 30, category: 'Bread & Bakery', emoji: '🥐' },
  { name: 'Doughnuts', value: 50, category: 'Bread & Bakery', emoji: '🍩' },
  { name: 'Cupcakes', value: 80, category: 'Bread & Bakery', emoji: '🧁' },
  { name: 'Biscuits', value: 50, category: 'Bread & Bakery', emoji: '🍪' },
  { name: 'Cookies', value: 60, category: 'Bread & Bakery', emoji: '🍪' },
  { name: 'Crackers', value: 70, category: 'Bread & Bakery', emoji: '🥨' },
  { name: 'Cake', value: 450, category: 'Bread & Bakery', emoji: '🍰' },
  { name: 'Fresh milk 500ml', value: 60, category: 'Milk & Dairy', emoji: '🥛' },
  { name: 'Fresh milk 1L', value: 120, category: 'Milk & Dairy', emoji: '🥛' },
  { name: 'Long-life milk', value: 150, category: 'Milk & Dairy', emoji: '🥛' },
  { name: 'Yoghurt', value: 100, category: 'Milk & Dairy', emoji: '🍶' },
  { name: 'Drinking yoghurt', value: 80, category: 'Milk & Dairy', emoji: '🍶' },
  { name: 'Cheese', value: 250, category: 'Milk & Dairy', emoji: '🧀' },
  { name: 'Cream', value: 180, category: 'Milk & Dairy', emoji: '🥛' },
  { name: 'Sour milk', value: 90, category: 'Milk & Dairy', emoji: '🥛' },
  { name: 'Milk powder', value: 300, category: 'Milk & Dairy', emoji: '🥛' },
  { name: 'Condensed milk', value: 200, category: 'Milk & Dairy', emoji: '🥛' },
  { name: 'Tea leaves', value: 200, category: 'Tea & Coffee', emoji: '🍵' },
  { name: 'Tea bags', value: 180, category: 'Tea & Coffee', emoji: '🍵' },
  { name: 'Instant coffee', value: 350, category: 'Tea & Coffee', emoji: '☕' },
  { name: 'Ground coffee', value: 400, category: 'Tea & Coffee', emoji: '☕' },
  { name: 'Cocoa powder', value: 250, category: 'Tea & Coffee', emoji: '🍫' },
  { name: 'Drinking chocolate', value: 220, category: 'Tea & Coffee', emoji: '🍫' },
  { name: 'Green tea', value: 280, category: 'Tea & Coffee', emoji: '🍵' },
  { name: 'Herbal tea', value: 260, category: 'Tea & Coffee', emoji: '🍵' },
  { name: 'Coffee creamer', value: 190, category: 'Tea & Coffee', emoji: '☕' },
  { name: 'Sugar sachets', value: 120, category: 'Tea & Coffee', emoji: '🍬' },
  { name: 'Coca-Cola', value: 80, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Fanta Orange', value: 80, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Sprite', value: 80, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Pepsi', value: 80, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Mountain Dew', value: 90, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Mirinda', value: 80, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Soda water', value: 70, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Tonic water', value: 90, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Ginger ale', value: 85, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Club soda', value: 75, category: 'Soft Drinks', emoji: '🥤' },
  { name: 'Orange juice', value: 120, category: 'Juices', emoji: '🧃' },
  { name: 'Mango juice', value: 120, category: 'Juices', emoji: '🧃' },
  { name: 'Apple juice', value: 120, category: 'Juices', emoji: '🧃' },
  { name: 'Mixed fruit juice', value: 130, category: 'Juices', emoji: '🧃' },
  { name: 'Pineapple juice', value: 120, category: 'Juices', emoji: '🧃' },
  { name: 'Passion juice', value: 120, category: 'Juices', emoji: '🧃' },
  { name: 'Tropical juice', value: 130, category: 'Juices', emoji: '🧃' },
  { name: 'Lemon juice', value: 100, category: 'Juices', emoji: '🧃' },
  { name: 'Tomato juice', value: 110, category: 'Juices', emoji: '🧃' },
  { name: 'Juice cartons', value: 150, category: 'Juices', emoji: '🧃' },
  { name: 'Bottled water 500ml', value: 50, category: 'Water', emoji: '💧' },
  { name: 'Bottled water 1L', value: 80, category: 'Water', emoji: '💧' },
  { name: 'Bottled water 5L', value: 300, category: 'Water', emoji: '💧' },
  { name: 'Mineral water', value: 100, category: 'Water', emoji: '💧' },
  { name: 'Sparkling water', value: 120, category: 'Water', emoji: '💧' },
  { name: 'Potato crisps', value: 60, category: 'Snacks', emoji: '🍟' },
  { name: 'Cheese puffs', value: 70, category: 'Snacks', emoji: '🧀' },
  { name: 'Popcorn', value: 50, category: 'Snacks', emoji: '🍿' },
  { name: 'Groundnuts', value: 80, category: 'Snacks', emoji: '🥜' },
  { name: 'Cashew nuts', value: 250, category: 'Snacks', emoji: '🥜' },
  { name: 'Peanuts', value: 70, category: 'Snacks', emoji: '🥜' },
  { name: 'Trail mix', value: 180, category: 'Snacks', emoji: '🥜' },
  { name: 'Chewing gum', value: 40, category: 'Snacks', emoji: '🍬' },
  { name: 'Mint sweets', value: 50, category: 'Snacks', emoji: '🍬' },
  { name: 'Lollipops', value: 30, category: 'Snacks', emoji: '🍭' },
  { name: 'Chocolate bar', value: 80, category: 'Confectionery', emoji: '🍫' },
  { name: 'Chocolate box', value: 350, category: 'Confectionery', emoji: '🍫' },
  { name: 'Candy', value: 60, category: 'Confectionery', emoji: '🍬' },
  { name: 'Toffee', value: 50, category: 'Confectionery', emoji: '🍬' },
  { name: 'Jelly sweets', value: 70, category: 'Confectionery', emoji: '🍬' },
  { name: 'Wafer biscuits', value: 60, category: 'Confectionery', emoji: '🍪' },
  { name: 'Marshmallows', value: 90, category: 'Confectionery', emoji: '☁️' },
  { name: 'Caramel sweets', value: 70, category: 'Confectionery', emoji: '🍬' },
  { name: 'Mints', value: 40, category: 'Confectionery', emoji: '🍬' },
  { name: 'Bubble gum', value: 30, category: 'Confectionery', emoji: '🫧' },
  { name: 'Baked beans', value: 120, category: 'Canned Foods', emoji: '🥫' },
  { name: 'Green peas', value: 100, category: 'Canned Foods', emoji: '🥫' },
  { name: 'Sweet corn', value: 110, category: 'Canned Foods', emoji: '🥫' },
  { name: 'Tomato paste', value: 90, category: 'Canned Foods', emoji: '🥫' },
  { name: 'Tuna', value: 280, category: 'Canned Foods', emoji: '🐟' },
  { name: 'Sardines', value: 180, category: 'Canned Foods', emoji: '🐟' },
  { name: 'Corned beef', value: 320, category: 'Canned Foods', emoji: '🥩' },
  { name: 'Coconut milk', value: 150, category: 'Canned Foods', emoji: '🥥' },
  { name: 'Mixed vegetables', value: 130, category: 'Canned Foods', emoji: '🥫' },
  { name: 'Baked beans in tomato sauce', value: 140, category: 'Canned Foods', emoji: '🥫' },
  { name: 'Black pepper', value: 120, category: 'Spices', emoji: '🌶️' },
  { name: 'Curry powder', value: 150, category: 'Spices', emoji: '🌶️' },
  { name: 'Turmeric', value: 100, category: 'Spices', emoji: '🌶️' },
  { name: 'Cinnamon', value: 130, category: 'Spices', emoji: '🌶️' },
  { name: 'Ginger powder', value: 110, category: 'Spices', emoji: '🌶️' },
  { name: 'Garlic powder', value: 100, category: 'Spices', emoji: '🧄' },
  { name: 'Paprika', value: 140, category: 'Spices', emoji: '🌶️' },
  { name: 'Mixed spice', value: 120, category: 'Spices', emoji: '🌶️' },
  { name: 'Pilau masala', value: 160, category: 'Spices', emoji: '🌶️' },
  { name: 'Chilli powder', value: 90, category: 'Spices', emoji: '🌶️' },
  { name: 'Bar soap', value: 40, category: 'Cleaning Products', emoji: '🧼' },
  { name: 'Bathing soap', value: 60, category: 'Cleaning Products', emoji: '🧼' },
  { name: 'Liquid soap', value: 180, category: 'Cleaning Products', emoji: '🧴' },
  { name: 'Laundry detergent', value: 350, category: 'Cleaning Products', emoji: '🧺' },
  { name: 'Washing powder', value: 280, category: 'Cleaning Products', emoji: '🧺' },
  { name: 'Fabric softener', value: 220, category: 'Cleaning Products', emoji: '🧺' },
  { name: 'Bleach', value: 150, category: 'Cleaning Products', emoji: '🧹' },
  { name: 'Dishwashing liquid', value: 160, category: 'Cleaning Products', emoji: '🍽️' },
  { name: 'Scouring powder', value: 120, category: 'Cleaning Products', emoji: '🧹' },
  { name: 'Toilet cleaner', value: 200, category: 'Cleaning Products', emoji: '🚽' },
  { name: 'Toothpaste', value: 120, category: 'Personal Care', emoji: '🪥' },
  { name: 'Toothbrush', value: 80, category: 'Personal Care', emoji: '🪥' },
  { name: 'Mouthwash', value: 250, category: 'Personal Care', emoji: '🪥' },
  { name: 'Dental floss', value: 150, category: 'Personal Care', emoji: '🪥' },
  { name: 'Shampoo', value: 300, category: 'Personal Care', emoji: '🧴' },
  { name: 'Conditioner', value: 280, category: 'Personal Care', emoji: '🧴' },
  { name: 'Hair oil', value: 180, category: 'Personal Care', emoji: '💇' },
  { name: 'Body lotion', value: 250, category: 'Personal Care', emoji: '🧴' },
  { name: 'Petroleum jelly', value: 120, category: 'Personal Care', emoji: '🧴' },
  { name: 'Deodorant', value: 220, category: 'Personal Care', emoji: '🧴' },
  { name: 'Baby diapers', value: 450, category: 'Baby Products', emoji: '👶' },
  { name: 'Baby wipes', value: 200, category: 'Baby Products', emoji: '👶' },
  { name: 'Baby lotion', value: 250, category: 'Baby Products', emoji: '👶' },
  { name: 'Baby powder', value: 180, category: 'Baby Products', emoji: '👶' },
  { name: 'Baby soap', value: 150, category: 'Baby Products', emoji: '👶' },
  { name: 'Baby shampoo', value: 200, category: 'Baby Products', emoji: '👶' },
  { name: 'Baby oil', value: 220, category: 'Baby Products', emoji: '👶' },
  { name: 'Baby cereal', value: 280, category: 'Baby Products', emoji: '👶' },
  { name: 'Feeding bottle', value: 350, category: 'Baby Products', emoji: '🍼' },
  { name: 'Pacifier', value: 120, category: 'Baby Products', emoji: '👶' },
  { name: 'Paracetamol', value: 80, category: 'Health', emoji: '💊' },
  { name: 'Ibuprofen', value: 120, category: 'Health', emoji: '💊' },
  { name: 'Vitamin C', value: 250, category: 'Health', emoji: '💊' },
  { name: 'Multivitamins', value: 350, category: 'Health', emoji: '💊' },
  { name: 'Bandages', value: 60, category: 'Health', emoji: '🩹' },
  { name: 'Cotton wool', value: 80, category: 'Health', emoji: '🩹' },
  { name: 'Antiseptic', value: 150, category: 'Health', emoji: '💊' },
  { name: 'Hand sanitizer', value: 200, category: 'Health', emoji: '🧴' },
  { name: 'Face masks', value: 120, category: 'Health', emoji: '😷' },
  { name: 'Thermometer', value: 450, category: 'Health', emoji: '🌡️' },
  { name: 'Toilet paper', value: 180, category: 'Household', emoji: '🧻' },
  { name: 'Paper towels', value: 150, category: 'Household', emoji: '🧻' },
  { name: 'Aluminium foil', value: 120, category: 'Household', emoji: '🫙' },
  { name: 'Cling film', value: 100, category: 'Household', emoji: '🫙' },
  { name: 'Garbage bags', value: 200, category: 'Household', emoji: '🗑️' },
  { name: 'Matches', value: 40, category: 'Household', emoji: '🔥' },
  { name: 'Candles', value: 120, category: 'Household', emoji: '🕯️' },
  { name: 'Batteries AA', value: 180, category: 'Household', emoji: '🔋' },
  { name: 'Batteries AAA', value: 180, category: 'Household', emoji: '🔋' },
  { name: 'Light bulbs', value: 250, category: 'Household', emoji: '💡' },
  { name: 'Exercise book', value: 80, category: 'Stationery', emoji: '📓' },
  { name: 'Notebook', value: 150, category: 'Stationery', emoji: '📓' },
  { name: 'Ballpoint pen', value: 40, category: 'Stationery', emoji: '🖊️' },
  { name: 'Pencil', value: 30, category: 'Stationery', emoji: '✏️' },
  { name: 'Eraser', value: 30, category: 'Stationery', emoji: '🧽' },
  { name: 'Sharpener', value: 40, category: 'Stationery', emoji: '✏️' },
  { name: 'Ruler', value: 50, category: 'Stationery', emoji: '📏' },
  { name: 'Marker pen', value: 80, category: 'Stationery', emoji: '🖊️' },
  { name: 'Glue stick', value: 60, category: 'Stationery', emoji: '🧴' },
  { name: 'Stapler', value: 250, category: 'Stationery', emoji: '📎' },
  { name: 'Dog food', value: 450, category: 'Pet Products', emoji: '🐕' },
  { name: 'Cat food', value: 420, category: 'Pet Products', emoji: '🐈' },
  { name: 'Bird feed', value: 200, category: 'Pet Products', emoji: '🐦' },
  { name: 'Fish food', value: 150, category: 'Pet Products', emoji: '🐟' },
  { name: 'Pet shampoo', value: 280, category: 'Pet Products', emoji: '🐕' },
  { name: 'Frozen chicken', value: 550, category: 'Frozen Foods', emoji: '🍗' },
  { name: 'Frozen beef', value: 650, category: 'Frozen Foods', emoji: '🥩' },
  { name: 'Frozen fish', value: 400, category: 'Frozen Foods', emoji: '🐟' },
  { name: 'Frozen sausages', value: 350, category: 'Frozen Foods', emoji: '🌭' },
  { name: 'Frozen vegetables', value: 200, category: 'Frozen Foods', emoji: '🥦' },
  { name: 'Bananas', value: 60, category: 'Fruits & Vegetables', emoji: '🍌' },
  { name: 'Apples', value: 80, category: 'Fruits & Vegetables', emoji: '🍎' },
  { name: 'Oranges', value: 70, category: 'Fruits & Vegetables', emoji: '🍊' },
  { name: 'Tomatoes', value: 50, category: 'Fruits & Vegetables', emoji: '🍅' },
  { name: 'Onions', value: 40, category: 'Fruits & Vegetables', emoji: '🧅' },
  { name: 'Potatoes', value: 60, category: 'Fruits & Vegetables', emoji: '🥔' },
  { name: 'Cabbage', value: 40, category: 'Fruits & Vegetables', emoji: '🥬' },
  { name: 'Carrots', value: 50, category: 'Fruits & Vegetables', emoji: '🥕' },
  { name: 'Avocados', value: 30, category: 'Fruits & Vegetables', emoji: '🥑' },
  { name: 'Lemons', value: 20, category: 'Fruits & Vegetables', emoji: '🍋' },
  { name: 'Airtime scratch cards', value: 100, category: 'Miscellaneous', emoji: '📱' },
  { name: 'Phone charger', value: 350, category: 'Miscellaneous', emoji: '🔌' },
  { name: 'USB cable', value: 280, category: 'Miscellaneous', emoji: '🔌' },
  { name: 'Umbrella', value: 400, category: 'Miscellaneous', emoji: '☂️' },
  { name: 'Reusable shopping bag', value: 150, category: 'Miscellaneous', emoji: '🛍️' }
];

export const DEFAULT_ITEM_CATEGORIES = Array.from(new Set(DEFAULT_ITEMS.map(i => i.category)));

const colorForCategory = (category: string): string => {
  const colors: Record<string, string> = {
    'Food Staples': '#F59E0B',
    'Bread & Bakery': '#EF4444',
    'Milk & Dairy': '#3B82F6',
    'Tea & Coffee': '#8B5CF6',
    'Soft Drinks': '#EC4899',
    'Juices': '#F97316',
    'Water': '#14B8A6',
    'Snacks': '#6366F1',
    'Confectionery': '#84CC16',
    'Canned Foods': '#EF4444',
    'Spices': '#F59E0B',
    'Cleaning Products': '#10B981',
    'Personal Care': '#3B82F6',
    'Baby Products': '#EC4899',
    'Health': '#F97316',
    'Household': '#6366F1',
    'Stationery': '#8B5CF6',
    'Pet Products': '#14B8A6',
    'Frozen Foods': '#EF4444',
    'Fruits & Vegetables': '#84CC16',
    'Miscellaneous': '#6B7280'
  };
  return colors[category] || '#6B7280';
};

export const generateDefaultItemImage = (name: string, category = ''): string => {
  const item = DEFAULT_ITEMS.find(i => i.name === name);
  const emoji = item?.emoji || '📦';
  const color = colorForCategory(item?.category || category || 'Miscellaneous');

  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  }
  const letter = name.charAt(0).toUpperCase();

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200">
    <rect width="200" height="200" fill="${color}" rx="20"/>
    <text x="100" y="130" font-family="Arial, sans-serif" font-size="90" text-anchor="middle">${emoji}</text>
    <text x="100" y="170" font-family="Arial, sans-serif" font-size="24" font-weight="bold" fill="white" text-anchor="middle" opacity="0.9">${letter}</text>
    <circle cx="160" cy="40" r="24" fill="rgba(0,0,0,0.3)"/>
    <text x="160" y="48" font-family="Arial, sans-serif" font-size="24" font-weight="bold" fill="white" text-anchor="middle">${Math.abs(hash) % 10}</text>
  </svg>`;

  return 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(svg)));
};

export const getDefaultItemImage = (name: string): string => generateDefaultItemImage(name);

export const getDefaultItemsByCategory = (category: string): DefaultItem[] =>
  DEFAULT_ITEMS.filter(i => i.category === category);

export const getAllDefaultItems = (): DefaultItem[] => DEFAULT_ITEMS;
